# Generated by Django 3.2.3 on 2021-05-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('title', models.CharField(max_length=50)),
                ('sous_title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='image_contact')),
            ],
            options={
                'verbose_name': 'BannerContact',
                'verbose_name_plural': 'BannerContacts',
            },
        ),
        migrations.CreateModel(
            name='BannerWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('title', models.CharField(max_length=50)),
                ('sous_title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='image_work')),
            ],
            options={
                'verbose_name': 'BannerWork',
                'verbose_name_plural': 'BannerWorks',
            },
        ),
        migrations.CreateModel(
            name='But',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('title', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'But',
                'verbose_name_plural': 'Buts',
            },
        ),
        migrations.CreateModel(
            name='Choose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('title', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Choose',
                'verbose_name_plural': 'Chooses',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('title', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('title', models.CharField(max_length=50)),
                ('sous_title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AlterField(
            model_name='bannerabout',
            name='image',
            field=models.FileField(upload_to='image_about'),
        ),
    ]
