# Generated by Django 3.2.3 on 2021-05-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0002_auto_20210522_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='but',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='but',
            name='sous_title',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
