# Generated by Django 3.2.3 on 2021-05-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0003_auto_20210522_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='choose',
            name='image',
            field=models.FileField(default=1, upload_to='image_choose'),
            preserve_default=False,
        ),
    ]
