# Generated by Django 3.2.3 on 2021-05-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0004_choose_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('phone', models.CharField(max_length=250)),
                ('copyright', models.CharField(max_length=250)),
                ('name_site', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('description_team', models.TextField()),
                ('description_footer', models.TextField()),
                ('description_creative', models.TextField()),
                ('description_transform', models.TextField()),
                ('description_newsletter', models.TextField()),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Websites',
            },
        ),
    ]
