# Generated by Django 3.2.3 on 2021-05-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0006_auto_20210523_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='but',
            name='sous_title',
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
