# Generated by Django 3.2.3 on 2021-05-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0002_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assitance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('title', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('icon', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Assitance',
                'verbose_name_plural': 'Assitances',
            },
        ),
        migrations.CreateModel(
            name='CreateSucce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('title', models.CharField(max_length=50)),
                ('sous_title', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'CreateSucce',
                'verbose_name_plural': 'CreateSucces',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('name', models.CharField(max_length=250)),
                ('icon', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'CreateSucce',
                'verbose_name_plural': 'CreateSucces',
            },
        ),
    ]
