# Generated by Django 3.2.3 on 2021-05-23 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0003_assitance_createsucce_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Social', 'verbose_name_plural': 'Socials'},
        ),
    ]
