# Generated by Django 3.2.3 on 2021-05-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0005_social_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0)),
                ('period', models.CharField(max_length=255)),
                ('activate', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pack',
                'verbose_name_plural': 'Packs',
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('label', models.CharField(max_length=255)),
                ('label_activate', models.BooleanField(default=True)),
                ('pack', models.ManyToManyField(related_name='advantage_pack', to='contactapp.Pack')),
            ],
            options={
                'verbose_name': 'Advantage',
                'verbose_name_plural': 'Advantages',
            },
        ),
    ]
